export const GET_PLAYER = "GET_PLAYER";
export const ADD_PLAYER = "ADD_PLAYER";
export const EDIT_PLAYER = "EDIT_PLAYER";
export const DELETE_PLAYER = "DELETE_PLAYER";

export const GET_PLAYER_SUCCESS = "GET_PLAYER_SUCCESS";
export const ADD_PLAYER_SUCCESS = "ADD_PLAYER_SUCCESS";
export const EDIT_PLAYER_SUCCESS = "EDIT_PLAYER_SUCCESS";
export const DELETE_PLAYER_SUCCESS = "DELETE_PLAYER_SUCCESS";